version: 2
jobs:
    lint:
        docker:
            - image: circleci/node:9.3
        steps:
            - checkout
            - restore_cache:
                key: node-modules-{{ checksum  "package.json" }}
            - run:
                name: Install modules
                command: npm install
            - save_cache:
                key: node-modules-{{ checksum "package.json" }}
                paths:
                    - node_modules
            - run:
                name: Lint
                command: npm run lint

    test:
        docker:
            - image: circleci/node:9.3
        steps:
            - checkout
            - restore_cache:
                key: node-modules-{{ checksum  "package.json" }}
            - run:
                name: Install modules
                command: npm install
            - save_cache:
                key: node-modules-{{ checksum "package.json" }}
                paths:
                    - node_modules
            - run:
                name: Run tests
                command: npm test
            - store_test_results:
                path: transpiled/junit/
            - store_artifacts:
                path: transpiled/junit/
workflows:
    version: 2
    everything:
        jobs:
            - lint
            - test
